#application name 
spring.application.name=jewellery


#server to run
server.port=8080

#Postgres Configuration
spring.datasource.url=jdbc:PostgresSql://localhost:3306/jewellery
spring.datasource.username=postgres
spring.datasource.password=Jewellery_Postgres
spring.datasource.driver-class-name=org.postgresssql.Driver

#Spring data jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

